services:
  nodered:
    image: nodered/node-red
    volumes:
      - newmyNodeREDdata:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 1880:1880
  # nodeapp:
  #   build: nodeapp/.
  #   # extra_hosts:
  #   #   - "host.docker.internal:host-gateway"
  #   environment:
  #     - HOST_LAN_IP=${HOST_LAN_IP}
  #   ports:
  #     - 8000
  mqtt:
    image: eclipse-mosquitto
    volumes:
      - .\MQTTconfig:/mosquitto/config
      - .\MQTTdata:/mosquitto/data
      - .\MQTTlogs:/mosquitto/log
    ports:
      - 1883:1883
  oauth:
    build: oauth_new/.
    restart: unless-stopped
    volumes:
      - .\oauth_new\etc\js:/usr/src/app/etc/js
      - .\oauth_new\server.js:/usr/src/app/server.js
    ports:
      - 3000
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - .\ngrok.yml:/etc/ngrok.yml

volumes:
  newmyNodeREDdata:
  MQTTconfig:
  MQTTdata:
  MQTTlogs:
